-- -------------------------------------------------------------
-- TablePlus 3.12.4(360)
--
-- https://tableplus.com/
--
-- Database: botscape
-- Generation Time: 2021-03-17 11:45:10.6990
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


DROP TABLE IF EXISTS `history`;
CREATE TABLE `history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `time` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `currentPrice` float DEFAULT NULL,
  `greenPrice` float DEFAULT NULL,
  `action` varchar(255) DEFAULT NULL,
  `actionTaken` varchar(255) DEFAULT NULL,
  `actionValue` float DEFAULT NULL,
  `market` varchar(255) DEFAULT NULL,
  `tradeId` varchar(255) DEFAULT NULL,
  `avgActionPrice` float DEFAULT NULL,
  `buyActionPrice` float DEFAULT NULL,
  `sellActionPrice` float DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `predictions`;
CREATE TABLE `predictions` (
  `key` varchar(10) NOT NULL,
  `value` float NOT NULL,
  UNIQUE KEY `key` (`key`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `trades`;
CREATE TABLE `trades` (
  `id` bigint(20) NOT NULL,
  `amount` float DEFAULT NULL,
  `date` int(11) DEFAULT NULL,
  `date_ms` bigint(20) DEFAULT NULL,
  `price` float DEFAULT NULL,
  `type` varchar(4) DEFAULT NULL,
  `market` varchar(7) DEFAULT NULL,
  `updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `p_fiveSec_avgPrice` float DEFAULT NULL,
  `p_fiveSec_highPrice` float DEFAULT NULL,
  `p_fiveSec_lowPrice` float DEFAULT NULL,
  `p_fiveSec_startPrice` float DEFAULT NULL,
  `p_fiveSec_endPrice` float DEFAULT NULL,
  `p_fiveSec_changeReal` float DEFAULT NULL,
  `p_fiveSec_changePercent` float DEFAULT NULL,
  `p_fiveSec_travelReal` float DEFAULT NULL,
  `p_fiveSec_travelPercent` float DEFAULT NULL,
  `p_fiveSec_volumePrMin` float DEFAULT NULL,
  `p_fiveSec_tradesPrMin` float DEFAULT NULL,
  `p_fiveSec_buysPrMin` float DEFAULT NULL,
  `p_fiveSec_sellsPrMin` float DEFAULT NULL,
  `p_tenSec_avgPrice` float DEFAULT NULL,
  `p_tenSec_highPrice` float DEFAULT NULL,
  `p_tenSec_lowPrice` float DEFAULT NULL,
  `p_tenSec_startPrice` float DEFAULT NULL,
  `p_tenSec_endPrice` float DEFAULT NULL,
  `p_tenSec_changeReal` float DEFAULT NULL,
  `p_tenSec_changePercent` float DEFAULT NULL,
  `p_tenSec_travelReal` float DEFAULT NULL,
  `p_tenSec_travelPercent` float DEFAULT NULL,
  `p_tenSec_volumePrMin` float DEFAULT NULL,
  `p_tenSec_tradesPrMin` float DEFAULT NULL,
  `p_tenSec_buysPrMin` float DEFAULT NULL,
  `p_tenSec_sellsPrMin` float DEFAULT NULL,
  `p_thirtySec_avgPrice` float DEFAULT NULL,
  `p_thirtySec_highPrice` float DEFAULT NULL,
  `p_thirtySec_lowPrice` float DEFAULT NULL,
  `p_thirtySec_startPrice` float DEFAULT NULL,
  `p_thirtySec_endPrice` float DEFAULT NULL,
  `p_thirtySec_changeReal` float DEFAULT NULL,
  `p_thirtySec_changePercent` float DEFAULT NULL,
  `p_thirtySec_travelReal` float DEFAULT NULL,
  `p_thirtySec_travelPercent` float DEFAULT NULL,
  `p_thirtySec_volumePrMin` float DEFAULT NULL,
  `p_thirtySec_tradesPrMin` float DEFAULT NULL,
  `p_thirtySec_buysPrMin` float DEFAULT NULL,
  `p_thirtySec_sellsPrMin` float DEFAULT NULL,
  `p_oneMin_avgPrice` float DEFAULT NULL,
  `p_oneMin_highPrice` float DEFAULT NULL,
  `p_oneMin_lowPrice` float DEFAULT NULL,
  `p_oneMin_startPrice` float DEFAULT NULL,
  `p_oneMin_endPrice` float DEFAULT NULL,
  `p_oneMin_changeReal` float DEFAULT NULL,
  `p_oneMin_changePercent` float DEFAULT NULL,
  `p_oneMin_travelReal` float DEFAULT NULL,
  `p_oneMin_travelPercent` float DEFAULT NULL,
  `p_oneMin_volumePrMin` float DEFAULT NULL,
  `p_oneMin_tradesPrMin` float DEFAULT NULL,
  `p_oneMin_buysPrMin` float DEFAULT NULL,
  `p_oneMin_sellsPrMin` float DEFAULT NULL,
  `p_threeMin_avgPrice` float DEFAULT NULL,
  `p_threeMin_highPrice` float DEFAULT NULL,
  `p_threeMin_lowPrice` float DEFAULT NULL,
  `p_threeMin_startPrice` float DEFAULT NULL,
  `p_threeMin_endPrice` float DEFAULT NULL,
  `p_threeMin_changeReal` float DEFAULT NULL,
  `p_threeMin_changePercent` float DEFAULT NULL,
  `p_threeMin_travelReal` float DEFAULT NULL,
  `p_threeMin_travelPercent` float DEFAULT NULL,
  `p_threeMin_volumePrMin` float DEFAULT NULL,
  `p_threeMin_tradesPrMin` float DEFAULT NULL,
  `p_threeMin_buysPrMin` float DEFAULT NULL,
  `p_threeMin_sellsPrMin` float DEFAULT NULL,
  `p_fiveMin_avgPrice` float DEFAULT NULL,
  `p_fiveMin_highPrice` float DEFAULT NULL,
  `p_fiveMin_lowPrice` float DEFAULT NULL,
  `p_fiveMin_startPrice` float DEFAULT NULL,
  `p_fiveMin_endPrice` float DEFAULT NULL,
  `p_fiveMin_changeReal` float DEFAULT NULL,
  `p_fiveMin_changePercent` float DEFAULT NULL,
  `p_fiveMin_travelReal` float DEFAULT NULL,
  `p_fiveMin_travelPercent` float DEFAULT NULL,
  `p_fiveMin_volumePrMin` float DEFAULT NULL,
  `p_fiveMin_tradesPrMin` float DEFAULT NULL,
  `p_fiveMin_buysPrMin` float DEFAULT NULL,
  `p_fiveMin_sellsPrMin` float DEFAULT NULL,
  `p_tenMin_avgPrice` float DEFAULT NULL,
  `p_tenMin_highPrice` float DEFAULT NULL,
  `p_tenMin_lowPrice` float DEFAULT NULL,
  `p_tenMin_startPrice` float DEFAULT NULL,
  `p_tenMin_endPrice` float DEFAULT NULL,
  `p_tenMin_changeReal` float DEFAULT NULL,
  `p_tenMin_changePercent` float DEFAULT NULL,
  `p_tenMin_travelReal` float DEFAULT NULL,
  `p_tenMin_travelPercent` float DEFAULT NULL,
  `p_tenMin_volumePrMin` float DEFAULT NULL,
  `p_tenMin_tradesPrMin` float DEFAULT NULL,
  `p_tenMin_buysPrMin` float DEFAULT NULL,
  `p_tenMin_sellsPrMin` float DEFAULT NULL,
  `p_fifteenMin_avgPrice` float DEFAULT NULL,
  `p_fifteenMin_highPrice` float DEFAULT NULL,
  `p_fifteenMin_lowPrice` float DEFAULT NULL,
  `p_fifteenMin_startPrice` float DEFAULT NULL,
  `p_fifteenMin_endPrice` float DEFAULT NULL,
  `p_fifteenMin_changeReal` float DEFAULT NULL,
  `p_fifteenMin_changePercent` float DEFAULT NULL,
  `p_fifteenMin_travelReal` float DEFAULT NULL,
  `p_fifteenMin_travelPercent` float DEFAULT NULL,
  `p_fifteenMin_volumePrMin` float DEFAULT NULL,
  `p_fifteenMin_tradesPrMin` float DEFAULT NULL,
  `p_fifteenMin_buysPrMin` float DEFAULT NULL,
  `p_fifteenMin_sellsPrMin` float DEFAULT NULL,
  `p_thirtyMin_avgPrice` float DEFAULT NULL,
  `p_thirtyMin_highPrice` float DEFAULT NULL,
  `p_thirtyMin_lowPrice` float DEFAULT NULL,
  `p_thirtyMin_startPrice` float DEFAULT NULL,
  `p_thirtyMin_endPrice` float DEFAULT NULL,
  `p_thirtyMin_changeReal` float DEFAULT NULL,
  `p_thirtyMin_changePercent` float DEFAULT NULL,
  `p_thirtyMin_travelReal` float DEFAULT NULL,
  `p_thirtyMin_travelPercent` float DEFAULT NULL,
  `p_thirtyMin_volumePrMin` float DEFAULT NULL,
  `p_thirtyMin_tradesPrMin` float DEFAULT NULL,
  `p_thirtyMin_buysPrMin` float DEFAULT NULL,
  `p_thirtyMin_sellsPrMin` float DEFAULT NULL,
  `p_sixtyMin_avgPrice` float DEFAULT NULL,
  `p_sixtyMin_highPrice` float DEFAULT NULL,
  `p_sixtyMin_lowPrice` float DEFAULT NULL,
  `p_sixtyMin_startPrice` float DEFAULT NULL,
  `p_sixtyMin_endPrice` float DEFAULT NULL,
  `p_sixtyMin_changeReal` float DEFAULT NULL,
  `p_sixtyMin_changePercent` float DEFAULT NULL,
  `p_sixtyMin_travelReal` float DEFAULT NULL,
  `p_sixtyMin_travelPercent` float DEFAULT NULL,
  `p_sixtyMin_volumePrMin` float DEFAULT NULL,
  `p_sixtyMin_tradesPrMin` float DEFAULT NULL,
  `p_sixtyMin_buysPrMin` float DEFAULT NULL,
  `p_sixtyMin_sellsPrMin` float DEFAULT NULL,
  `p_oneTwentyMin_avgPrice` float DEFAULT NULL,
  `p_oneTwentyMin_highPrice` float DEFAULT NULL,
  `p_oneTwentyMin_lowPrice` float DEFAULT NULL,
  `p_oneTwentyMin_startPrice` float DEFAULT NULL,
  `p_oneTwentyMin_endPrice` float DEFAULT NULL,
  `p_oneTwentyMin_changeReal` float DEFAULT NULL,
  `p_oneTwentyMin_changePercent` float DEFAULT NULL,
  `p_oneTwentyMin_travelReal` float DEFAULT NULL,
  `p_oneTwentyMin_travelPercent` float DEFAULT NULL,
  `p_oneTwentyMin_volumePrMin` float DEFAULT NULL,
  `p_oneTwentyMin_tradesPrMin` float DEFAULT NULL,
  `p_oneTwentyMin_buysPrMin` float DEFAULT NULL,
  `p_oneTwentyMin_sellsPrMin` float DEFAULT NULL,
  `f_fiveSec_changeReal` float DEFAULT NULL,
  `f_tenSec_changeReal` float DEFAULT NULL,
  `f_thirtySec_changeReal` float DEFAULT NULL,
  `f_oneMin_changeReal` float DEFAULT NULL,
  `f_threeMin_changeReal` float DEFAULT NULL,
  `f_fiveMin_changeReal` float DEFAULT NULL,
  `f_tenMin_changeReal` float DEFAULT NULL,
  `f_fifteenMin_changeReal` float DEFAULT NULL,
  `f_thirtyMin_changeReal` float DEFAULT NULL,
  `f_sixtyMin_changeReal` float DEFAULT NULL,
  `f_oneTwentyMin_changeReal` float DEFAULT NULL,
  `f_fiveSec_changePercent` float DEFAULT NULL,
  `f_tenSec_changePercent` float DEFAULT NULL,
  `f_thirtySec_changePercent` float DEFAULT NULL,
  `f_oneMin_changePercent` float DEFAULT NULL,
  `f_threeMin_changePercent` float DEFAULT NULL,
  `f_fiveMin_changePercent` float DEFAULT NULL,
  `f_tenMin_changePercent` float DEFAULT NULL,
  `f_fifteenMin_changePercent` float DEFAULT NULL,
  `f_thirtyMin_changePercent` float DEFAULT NULL,
  `f_sixtyMin_changePercent` float DEFAULT NULL,
  `f_oneTwentyMin_changePercent` float DEFAULT NULL,
  `f_oneTwentyMin_lowPrice` float DEFAULT NULL,
  `f_fiveSec_highPrice` float DEFAULT NULL,
  `f_tenSec_highPrice` float DEFAULT NULL,
  `f_thirtySec_highPrice` float DEFAULT NULL,
  `f_oneMin_highPrice` float DEFAULT NULL,
  `f_threeMin_highPrice` float DEFAULT NULL,
  `f_fiveMin_highPrice` float DEFAULT NULL,
  `f_tenMin_highPrice` float DEFAULT NULL,
  `f_fifteenMin_highPrice` float DEFAULT NULL,
  `f_thirtyMin_highPrice` float DEFAULT NULL,
  `f_sixtyMin_highPrice` float DEFAULT NULL,
  `f_oneTwentyMin_highPrice` float DEFAULT NULL,
  `f_fiveSec_lowPrice` float DEFAULT NULL,
  `f_tenSec_lowPrice` float DEFAULT NULL,
  `f_thirtySec_lowPrice` float DEFAULT NULL,
  `f_oneMin_lowPrice` float DEFAULT NULL,
  `f_threeMin_lowPrice` float DEFAULT NULL,
  `f_fiveMin_lowPrice` float DEFAULT NULL,
  `f_tenMin_lowPrice` float DEFAULT NULL,
  `f_fifteenMin_lowPrice` float DEFAULT NULL,
  `f_thirtyMin_lowPrice` float DEFAULT NULL,
  `f_sixtyMin_lowPrice` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `date` (`date`) USING BTREE,
  KEY `date_ms` (`date_ms`) USING BTREE,
  KEY `f_oneTwentyMin_changePercent` (`f_oneTwentyMin_changePercent`) USING BTREE,
  KEY `p_oneTwentyMin_changePercent` (`p_oneTwentyMin_changePercent`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;